/* Generated by re2c 4.5.1 on Mon Jun 22 16:17:17 2026 */
#line 1 "OmfgScript/omfg_script_parser.h.re"
#include <memory>
#include <cstddef>
#include <cstdlib>
#include <cstring>
#include <iostream>
using std::auto_ptr;

#include <boost/lexical_cast.hpp>
using boost::lexical_cast;
#include <string>
#include <map>
#include <stdexcept>
#include <iostream>
using std::cout;
using std::endl;
using std::string;
using std::map;

/*
IDENT : [A-Za-z][A-Za-z0-9]*
{
	CONSTRUCT(b, e) : str(b, e) {}
	
	virtual double toDouble()
	{ throw std::runtime_error("Object is not a double"); }
	
	virtual std::string const& toString()
	{ return str; }
	
	virtual std::list<TokenBase*> const& toList()
	{ throw std::runtime_error("Object is not a list"); }
	
	virtual TokenBase::Type::type type() { return TokenBase::Type::String; }
	
	std::string str;
} ;

NEWLINE : [\r\n]* ;

event<> = ON IDENT<name> LPARAN [parameters] RPARAN NEWLINE action* ;
*/

#define D(x) (cout << x << std::endl)

namespace OmfgScript{
template<class T>
struct TGrammar {
#define self (static_cast<T *>(this))
~TGrammar() { free(buffer); }
struct Token : public  TokenBase  { typedef std::auto_ptr<Token> ptr;

	Token(T& g_) : TokenBase(g_.getLoc()), g(g_) {}
	
	T& g;

virtual ~Token() {}
};

struct STRING : public Token {
typedef std::auto_ptr<STRING> ptr;
#define CONSTRUCT(b_, e_) STRING(T& g, char const* b_, char const* e_)

	CONSTRUCT(b, e) : Token(g), str(b, e) { }

	virtual std::string const& toString()
	{ return str; }
	
	virtual TokenBase::Type::type type() { return TokenBase::Type::String; }
	
	virtual std::ostream& output(std::ostream& s) { s << str; return s; }
	
	virtual void calcCRC(boost::crc_32_type& crc)
	{
		crc.process_bytes(str.data(), str.size());
	}
	
	std::string str;

#undef CONSTRUCT
};
struct INTEGER : public Token {
typedef std::auto_ptr<INTEGER> ptr;
#define CONSTRUCT(b_, e_) INTEGER(T& g, char const* b_, char const* e_)

	CONSTRUCT(b, e) : Token(g) { v = lexical_cast<int>(std::string(b, e)); }
	
	INTEGER(T& g, int i) : Token(g), v(i) {}
	
	virtual double toDouble()
	{ return v; }
	
	virtual int toInt()
	{ return v; }
	
	virtual TokenBase::Type::type type() { return TokenBase::Type::Int; }
	
	virtual std::ostream& output(std::ostream& s) { s << v; return s; }
	
	virtual void calcCRC(boost::crc_32_type& crc)
	{
		crc(v & 0xFF);
		crc((v >> 8) & 0xFF);
		crc((v >> 16) & 0xFF);
		crc((v >> 24) & 0xFF);
	}
	
	int v;

#undef CONSTRUCT
};
struct NUMBER : public Token {
typedef std::auto_ptr<NUMBER> ptr;
#define CONSTRUCT(b_, e_) NUMBER(T& g, char const* b_, char const* e_)

	CONSTRUCT(b, e) : Token(g) { v = lexical_cast<double>(std::string(b, e)); }
	
	virtual double toDouble()
	{ return v; }
	
	virtual int toInt()
	{
		this->g.semanticWarning("Number converted to integer may lose precision", this->loc);
		return static_cast<int>(v);
	}
	
	virtual TokenBase::Type::type type() { return TokenBase::Type::Double; }
	
	virtual std::ostream& output(std::ostream& s) { s << v; return s; }
	
	virtual void calcCRC(boost::crc_32_type& crc)
	{
		//TODO: Less tolerance
		int vi = (int)v;
		crc(vi & 0xFF);
		crc((vi >> 8) & 0xFF);
		crc((vi >> 16) & 0xFF);
		crc((vi >> 24) & 0xFF);
	}
	
	double v;

#undef CONSTRUCT
};
void next() {
#define YYCTYPE char
#define YYCURSOR curp
#define YYLIMIT limit
#define YYMARKER marker
#define YYFILL(n) fill(n)
retry:
begin = curp;
goto append; append:
#line 155 "OmfgScript/omfg_script_parser.h.re"

switch(state) {case 0:

#line 160 "<stdout>"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 6) YYFILL(6);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy1;
		case '\t':
		case '\r':
		case ' ': goto yy4;
		case '\n': goto yy5;
		case '"': goto yy6;
		case '#': goto yy7;
		case '(': goto yy9;
		case ')': goto yy10;
		case '*': goto yy11;
		case '+': goto yy12;
		case ',': goto yy13;
		case '-': goto yy14;
		case '/': goto yy16;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy17;
		case '<': goto yy19;
		case '=': goto yy20;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy21;
		case '[': goto yy24;
		case ']': goto yy25;
		case 'f': goto yy26;
		case 'o': goto yy27;
		case 't': goto yy28;
		case '{': goto yy29;
		case '}': goto yy30;
		default: goto yy2;
	}
yy1:
	++YYCURSOR;
#line 228 "OmfgScript/omfg_script_parser.h.re"
	{ cur = 0; return; }
#line 255 "<stdout>"
yy2:
	++YYCURSOR;
yy3:
#line 229 "OmfgScript/omfg_script_parser.h.re"
	{ semanticError(std::string("Unknown character '") + *begin + "'"); goto retry; }
#line 261 "<stdout>"
yy4:
	++YYCURSOR;
#line 176 "OmfgScript/omfg_script_parser.h.re"
	{ 
#define linecounter() (++this->line)
#define skip() goto retry
#define append() goto append
#define setstate(x_) (state = (x_))
 skip(); 
#undef setstate
#undef append
#undef skip
#undef linecounter
 cur = 19; return; }
#line 276 "<stdout>"
yy5:
	++YYCURSOR;
#line 198 "OmfgScript/omfg_script_parser.h.re"
	{ 
#define linecounter() (++this->line)
#define skip() goto retry
#define append() goto append
#define setstate(x_) (state = (x_))
 linecounter(); skip(); 
#undef setstate
#undef append
#undef skip
#undef linecounter
 cur = 21; return; }
#line 291 "<stdout>"
yy6:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= 0x00) goto yy3;
	goto yy32;
yy7:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00:
		case '\n':
		case '\r': goto yy8;
		default: goto yy7;
	}
yy8:
#line 187 "OmfgScript/omfg_script_parser.h.re"
	{ 
#define linecounter() (++this->line)
#define skip() goto retry
#define append() goto append
#define setstate(x_) (state = (x_))
 skip(); 
#undef setstate
#undef append
#undef skip
#undef linecounter
 cur = 20; return; }
#line 319 "<stdout>"
yy9:
	++YYCURSOR;
#line 162 "OmfgScript/omfg_script_parser.h.re"
	{  cur = 5; return; }
#line 324 "<stdout>"
yy10:
	++YYCURSOR;
#line 163 "OmfgScript/omfg_script_parser.h.re"
	{  cur = 6; return; }
#line 329 "<stdout>"
yy11:
	++YYCURSOR;
#line 171 "OmfgScript/omfg_script_parser.h.re"
	{  cur = 14; return; }
#line 334 "<stdout>"
yy12:
	++YYCURSOR;
#line 169 "OmfgScript/omfg_script_parser.h.re"
	{  cur = 12; return; }
#line 339 "<stdout>"
yy13:
	++YYCURSOR;
#line 168 "OmfgScript/omfg_script_parser.h.re"
	{  cur = 11; return; }
#line 344 "<stdout>"
yy14:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy17;
		default: goto yy15;
	}
yy15:
#line 170 "OmfgScript/omfg_script_parser.h.re"
	{  cur = 13; return; }
#line 363 "<stdout>"
yy16:
	++YYCURSOR;
#line 172 "OmfgScript/omfg_script_parser.h.re"
	{  cur = 15; return; }
#line 368 "<stdout>"
yy17:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case '.': goto yy35;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy17;
		default: goto yy18;
	}
yy18:
#line 174 "OmfgScript/omfg_script_parser.h.re"
	{  cur = 17; curData.reset(new INTEGER(*self, begin, YYCURSOR)); return; }
#line 390 "<stdout>"
yy19:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '<': goto yy37;
		default: goto yy3;
	}
yy20:
	++YYCURSOR;
#line 161 "OmfgScript/omfg_script_parser.h.re"
	{  cur = 4; return; }
#line 401 "<stdout>"
yy21:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy22:
	switch (yych) {
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy21;
		default: goto yy23;
	}
yy23:
#line 173 "OmfgScript/omfg_script_parser.h.re"
	{  cur = 16; curData.reset(new STRING(*self, begin, YYCURSOR)); return; }
#line 479 "<stdout>"
yy24:
	++YYCURSOR;
#line 164 "OmfgScript/omfg_script_parser.h.re"
	{  cur = 7; return; }
#line 484 "<stdout>"
yy25:
	++YYCURSOR;
#line 165 "OmfgScript/omfg_script_parser.h.re"
	{  cur = 8; return; }
#line 489 "<stdout>"
yy26:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy38;
		default: goto yy22;
	}
yy27:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy39;
		default: goto yy22;
	}
yy28:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy41;
		default: goto yy22;
	}
yy29:
	++YYCURSOR;
#line 166 "OmfgScript/omfg_script_parser.h.re"
	{  cur = 9; return; }
#line 512 "<stdout>"
yy30:
	++YYCURSOR;
#line 167 "OmfgScript/omfg_script_parser.h.re"
	{  cur = 10; return; }
#line 517 "<stdout>"
yy31:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy32:
	switch (yych) {
		case 0x00: goto yy33;
		case '"': goto yy34;
		default: goto yy31;
	}
yy33:
	YYCURSOR = YYMARKER;
	goto yy3;
yy34:
	++YYCURSOR;
#line 209 "OmfgScript/omfg_script_parser.h.re"
	{ 
#define b (begin)
#define e (YYCURSOR)
 cur = 16; curData.reset(new STRING(*self, b + 1, e - 1)); return; 

#undef b
#undef e
}
#line 542 "<stdout>"
yy35:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy35;
		default: goto yy36;
	}
yy36:
#line 175 "OmfgScript/omfg_script_parser.h.re"
	{  cur = 18; curData.reset(new NUMBER(*self, begin, YYCURSOR)); return; }
#line 563 "<stdout>"
yy37:
	yych = *++YYCURSOR;
	switch (yych) {
		case '<': goto yy42;
		default: goto yy33;
	}
yy38:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy43;
		default: goto yy22;
	}
yy39:
	yych = *++YYCURSOR;
	switch (yych) {
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy21;
		default: goto yy40;
	}
yy40:
#line 160 "OmfgScript/omfg_script_parser.h.re"
	{  cur = 3; return; }
#line 650 "<stdout>"
yy41:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'u': goto yy44;
		default: goto yy22;
	}
yy42:
	++YYCURSOR;
#line 217 "OmfgScript/omfg_script_parser.h.re"
	{ 
#define linecounter() (++this->line)
#define skip() goto retry
#define append() goto append
#define setstate(x_) (state = (x_))
 setstate(1); skip(); 
#undef setstate
#undef append
#undef skip
#undef linecounter
 cur = 23; return; }
#line 671 "<stdout>"
yy43:
	yych = *++YYCURSOR;
	switch (yych) {
		case 's': goto yy45;
		default: goto yy22;
	}
yy44:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy46;
		default: goto yy22;
	}
yy45:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy48;
		default: goto yy22;
	}
yy46:
	yych = *++YYCURSOR;
	switch (yych) {
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy21;
		default: goto yy47;
	}
yy47:
#line 158 "OmfgScript/omfg_script_parser.h.re"
	{  cur = 1; return; }
#line 764 "<stdout>"
yy48:
	yych = *++YYCURSOR;
	switch (yych) {
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy21;
		default: goto yy49;
	}
yy49:
#line 159 "OmfgScript/omfg_script_parser.h.re"
	{  cur = 2; return; }
#line 839 "<stdout>"
}
#line 230 "OmfgScript/omfg_script_parser.h.re"

break;
case 1:

#line 846 "<stdout>"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy51;
		case '>': goto yy54;
		default: goto yy52;
	}
yy51:
	++YYCURSOR;
#line 263 "OmfgScript/omfg_script_parser.h.re"
	{ cur = 0; return; }
#line 860 "<stdout>"
yy52:
	++YYCURSOR;
yy53:
#line 252 "OmfgScript/omfg_script_parser.h.re"
	{ 
#define linecounter() (++this->line)
#define skip() goto retry
#define append() goto append
#define setstate(x_) (state = (x_))
 append(); 
#undef setstate
#undef append
#undef skip
#undef linecounter
 cur = 25; return; }
#line 876 "<stdout>"
yy54:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '>': goto yy55;
		default: goto yy53;
	}
yy55:
	yych = *++YYCURSOR;
	switch (yych) {
		case '>': goto yy57;
		default: goto yy56;
	}
yy56:
	YYCURSOR = YYMARKER;
	goto yy53;
yy57:
	++YYCURSOR;
#line 234 "OmfgScript/omfg_script_parser.h.re"
	{ 
#define linecounter() (++this->line)
#define skip() goto retry
#define append() goto append
#define setstate(x_) (state = (x_))
 setstate(0); 
#undef setstate
#undef append
#undef skip
#undef linecounter

#define b (begin)
#define e (YYCURSOR)
 cur = 16; curData.reset(new STRING(*self, b, e - 3)); return; 

#undef b
#undef e
}
#line 913 "<stdout>"
}
#line 265 "OmfgScript/omfg_script_parser.h.re"

break;
}
#undef YYCTYPE
#undef YYCURSOR
#undef YYLIMIT
#undef YYMARKER
#undef YYFILL
}
void fill(size_t s) {
size_t l = limit - begin;
if(buffer)
	memmove(buffer, begin, l);
size_t newSize = std::max(static_cast<size_t>(1024), l + s);
buffer = (char *)realloc(buffer, newSize);
size_t toRead = newSize - l;
size_t amountRead = self->read(&buffer[l], toRead);
if(amountRead == 0) { memset(&buffer[l], 0, toRead); }
else newSize = l+amountRead;
ptrdiff_t offs = buffer - begin;
curp += offs;
marker += offs;
begin = buffer;
limit = buffer + newSize;
}
struct ParsingAborted : public std::exception { };
void fatalError(std::string const& msg = "Syntax error") {
self->reportError(msg, self->getLoc());
throw ParsingAborted();
}
void syntaxError(std::string const& msg = "Syntax error") {
syntaxError(msg, self->getLoc());
}
void syntaxError(std::string const& msg, Location loc) {
self->reportError(msg, loc);
syncTokens = true;
error = true;
}
void semanticError(std::string const& msg = "Semantic error") {
semanticError(msg, self->getLoc());
}
void semanticError(std::string const& msg, Location loc) {
self->reportError(msg, loc);
error = true;
}
void semanticWarning(std::string const& msg = "Semantic warning") {
semanticWarning(msg, self->getLoc());
}
void semanticWarning(std::string const& msg, Location loc) {
self->reportError("warning: " + msg, loc);
}
bool matchToken(int token) {
if(syncTokens) {
while(cur != token && cur != 0) next();
if(cur == 0 && token != 0) fatalError("Unexpected end of file");
syncTokens = false;} else {
if(cur != token) {
syntaxError("Unexpected token");
return false;
 }}
return true; }
bool optionalMatch(int token) {
if(syncTokens) {
while(cur != token && cur != 0) next();
syncTokens = false;if(cur != token) return false;
} else {
if(cur != token) {
return false;
 }}
return true; }
bool full() { return cur == 0 && !error; }
void rule_action(EventDef* event, std::vector<BaseAction*>& actions) {
if(!matchToken(16)) return;
std::auto_ptr<STRING> name(static_cast<STRING*>(curData.release()));
next();

		ActionDef* action(self->getAction(name->str));
		if(!action)
		{
	
while(cur != 6 && cur != 0) next();
next();

		}
		else if((action->requireMask & event->provideMask) != action->requireMask)
		{
			semanticError("Event does not provide the necessary requirements for this action");
	
while(cur != 6 && cur != 0) next();
next();

		}
		else
		{
			auto_ptr<Parameters> param(new Parameters(action->paramDef, self->getLoc()));
	
if(!matchToken(5)) return;
next();
if(set_1[cur]) {
rule_parameters(*param);
}
if(!matchToken(6)) return;
next();

			param->checkParams();
			if(param->flags & Parameters::Error)
				semanticError("Malformed parameters", param->loc);
			else
				actions.push_back(self->createAction(action, param));
		}
	
}
void rule_event() {
if(!matchToken(3)) return;
next();
if(!matchToken(16)) return;
std::auto_ptr<STRING> name(static_cast<STRING*>(curData.release()));
next();

		EventDef* event(self->getEventDef(name->str));
		if(!event)
		{
	
while(cur != 3 && cur != 0) next();

		}
		else
		{
			auto_ptr<Parameters> param(new Parameters(event->paramDef, self->getLoc()));
	
if(!matchToken(5)) return;
next();
if(set_1[cur]) {
rule_parameters(*param);
}
if(!matchToken(6)) return;
next();
 std::vector<BaseAction*> actions; 
while((cur == 16)) {
rule_action(event, actions);
}

			param->checkParams();
			if(param->flags & Parameters::Error)
				semanticError("Malformed parameters", param->loc);
			else
				self->addEvent(event, param, actions);
		}
	
}
void rule_expr(TokenBase::ptr& a) {
 int t; TokenBase::ptr b; 
Location exprLoc(self->getLoc());
rule_term(a);
while(set_3[cur]) {
if((cur == 12)) {
next();
 t = 0; 
}
else if((cur == 13)) {
next();
 t = 1; 
}
else { syntaxError(); return; }
rule_term(b);

			switch(t)
			{
				case 0: a.reset( new Add(exprLoc, a.release(), b.release()) ); break;
				case 1: a.reset( new Sub(exprLoc, a.release(), b.release()) ); break;
			}
		
}
}
void rule_leaf(TokenBase::ptr& a) {
if((cur == 1)) {
next();
 a.reset(new INTEGER(*self, 1)); 
}
else if((cur == 2)) {
next();
 a.reset(new INTEGER(*self, 0)); 
}
else if((cur == 16)) {
std::auto_ptr<STRING> x(static_cast<STRING*>(curData.release()));
next();
if((cur == 5)) {
 auto_ptr<Func> l(new Func(self->getLoc(), x->str)); TokenBase::ptr el; 
next();
rule_leaf(el);
 l->add(el); 
while((cur == 11)) {
next();
rule_leaf(el);
 l->add(el); 
}
if(!matchToken(6)) return;
next();
 a = l; 
}
else if(true) {
 a = x; 
}
else { syntaxError(); return; }
}
else if((cur == 17)) {
a.reset(curData.release());
next();
}
else if((cur == 18)) {
a.reset(curData.release());
next();
}
else if((cur == 7)) {
 auto_ptr<List> l(new List(self->getLoc())); TokenBase::ptr el; 
next();
rule_expr(el);
 l->add(el); 
while((cur == 11)) {
next();
rule_expr(el);
 l->add(el); 
}
if(!matchToken(8)) return;
next();
 a = l; 
}
else if((cur == 5)) {
next();
rule_expr(a);
if(!matchToken(6)) return;
next();
}
else { syntaxError(); return; }
}
void rule_lines() {
while((cur == 16)) {
rule_prop();
}
while((cur == 3)) {
rule_event();
}
}
void rule_parameter(Parameters& params) {
 TokenBase::ptr v; 
Location paramLoc(self->getLoc());
if((cur == 16)) {
std::auto_ptr<STRING> name(static_cast<STRING*>(curData.release()));
next();
if((cur == 4)) {
next();
rule_expr(v);
 params.addParam(name->str, v, paramLoc); 
}
else if(true) {
 params.addParam(TokenBase::ptr(name), paramLoc); 
}
else { syntaxError(); return; }
}
else if(set_1[cur]) {
rule_expr(v);
 params.addParam(v, paramLoc); 
}
else { syntaxError(); return; }
}
void rule_parameters(Parameters& params) {
rule_parameter(params);
while((cur == 11)) {
next();
rule_parameter(params);
}
}
void rule_prop(std::string const& prefix = "") {
 TokenBase::ptr v; 
Location propLoc(self->getLoc());
if(!matchToken(16)) return;
std::auto_ptr<STRING> name(static_cast<STRING*>(curData.release()));
next();
if((cur == 4)) {
next();
rule_expr(v);
 self->property(prefix + name->str, v.release(), propLoc); 
}
else if((cur == 9)) {
next();
while((cur == 16)) {
rule_prop((*name).str + "_");
}
if(!matchToken(10)) return;
next();
}
else { syntaxError(); return; }
}
void rule_term(TokenBase::ptr& a) {
 int t; TokenBase::ptr b; 
Location termLoc(self->getLoc());
rule_leaf(a);
while(set_17[cur]) {
if((cur == 14)) {
next();
 t = 0; 
}
else if((cur == 15)) {
next();
 t = 1; 
}
else { syntaxError(); return; }
rule_leaf(b);

			switch(t)
			{
				case 0: a.reset( new Mul(termLoc, a.release(), b.release()) ); break;
				case 1: a.reset( new Div(termLoc, a.release(), b.release()) ); break;
			}
		
}
}
bool set_1[26];
bool set_3[26];
bool set_17[26];
TGrammar() : cur(-1), begin(0), marker(0), buffer(0), curp(0), limit(0), line(1), syncTokens(false), error(false), state(0) {
memset(set_1, 0, sizeof(bool)*26);
set_1[1] = true;
set_1[2] = true;
set_1[5] = true;
set_1[7] = true;
set_1[16] = true;
set_1[17] = true;
set_1[18] = true;
memset(set_3, 0, sizeof(bool)*26);
set_3[12] = true;
set_3[13] = true;
memset(set_17, 0, sizeof(bool)*26);
set_17[14] = true;
set_17[15] = true;
}
int cur;
std::auto_ptr<Token> curData;
char* curp;
char* limit;
char* marker;
char* begin;
char* buffer;
int line;
int state;
bool syncTokens;
bool error;
#undef self
};
}
