Import('env')

if not env['NO_PARSERS']:
	env.Parser('detail/gss-grammar.h', 'detail/gss-grammar.pg')
env.StaticLibrary(env.getLibName('omfggui'), env.getObjects(['detail', 'lua']))

# Build GUI tests alongside the library for debug builds
env.TestProgram('gui_tests', ['omfggui', 'glua', 'omfgconsole', 'luajit-5.1'])
