Import('env')

# Build test binary from all .cpp files in this directory
testEnv = env.Clone()

brew_prefix = '/home/linuxbrew/.linuxbrew'
testEnv.Append(
    CPPPATH=[brew_prefix + '/include', '#Net'],
    LIBPATH=[brew_prefix + '/lib', '#/lib/' + testEnv['MY_SUBFOLDER']],
    LIBS=['omfgnet', 'boost_unit_test_framework', 'enet'],
    LINKFLAGS=['-pthread']
)

testEnv.Program(
    '#/bin/' + testEnv['MY_SUBFOLDER'] + '/ztests',
    Glob('*.cpp')
)