Import('env')

env = env.Clone()
env.Append(LIBS = Split("""
	omfggui omfgnet omfghttp omfgconsole 
	omfgscript glua omfgutil omfgxbrz""")
	)

# Platform specific additions can go here if needed
# but SDL3 and others are already added in SConstruct

exename = 'gusanos'
env.Program(env.getBinName(exename),
    env.getObjects() +
    env.getObjects('lua') +
	env.getObjects('blitters') +
	env.getObjects('loaders'))
