Import('env')

env = env.Clone()
env.Append(LIBS = Split("""
	renderLoaders omfgutil boost_filesystem""")
	)

# SDL3/Allegro replacement handled in SConstruct or eventually removed
# but for now we just remove the old allegro-config call.

env.Program(env.getBinName('lighter'),
    env.getObjects() + [env.Object('../Goop/allegro_compat.cpp')])
